#!/usr/bin/python

import pymysql

# Open database connection
db = pymysql.connect("localhost","root","","fluffy" )

# prepare a cursor object using cursor() method
cursor = db.cursor()

# execute SQL query using execute() method.
cursor.execute("SELECT * FROM criminals")

# Fetch a single row using fetchone() method.
data = cursor.fetchall()
print(data)

# disconnect from server
db.close()